### ISSUE TITLE
apt downloads do not disconnect

### ISSUE THREAD

**Issue by tkluck-booking** [tkluck/pac4cli#13]
I've observed that when apt downloads indexes or packages, it gets stuck at 100% download, waiting for a timeout instead of proceeding to download the next package.

My hypothesis is that pac4cli does not properly disconnect the apt -> pac4cli connection when the pac4cli -> server connection is being dropped by the server.

This is when downloading over http. I haven't validated whether it's using CONNECT or just GET, but I suspect the latter.

**Comment by tkluck-booking** [comment]
Should probably validate whether the twisted package / us properly [adhere to this spec here][spec].

[spec]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10

**Comment by tkluck** [comment]
-> #37
