### ISSUE TITLE
Need txdbus built for Ubuntu 18.04

### ISSUE THREAD

**Issue by brianj29** [tkluck/pac4cli#20]
In the Ubuntu PPA, pac4cli is being built for 18.04, but txdbus is not.  So I get an error while trying to install:

```
laptop1> sudo apt-get install pac4cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pac4cli : Depends: python3-txdbus but it is not installable
E: Unable to correct problems, you have held broken packages.

```
I must not have noticed this before, since I had had to force the 17.10 PPA to install pac4cli.  That must have installed txdbus.  Then when I removed pac4cli and switched to the 18.04 PPA, txdbus was already present, so I didn't get a dependency error.  But now I'm installing on a fresh system, so the error occurs.

If you could update the PPA, I'd appreciate it.

Thanks,
Brian Johnson

**Comment by brianj29** [comment]
Same goes for systemd-cython, if that's needed by pac4cli.

Thanks, Brian

**Comment by tkluck** [comment]
Thanks! Fired off the builds. I'll leave the issue open; could you close it once you've verified the install works for you now?

**Comment by tkluck** [comment]
@brianj29 I could also move the daily build recipes and the ppa to a team space and make you a member of that team. Advantage would be that I'm not a bus factor. Downside is that the ppa's url changes. What do you think?

**Comment by brianj29** [comment]
Works now.  Thanks!
I don't need to be part of a team for pac4cli, at least not at this time.  I doubt I will do any more development on it.  But thanks for the offer.
