### ISSUE TITLE
dbus-python problem on OSX?

### ISSUE THREAD

**Issue by gil** [tkluck/pac4cli#27]
Hey, don't know what's the best way to fix this (or if it needs to be fixed), but I was having problems when trying to install dbus-puthon on Mac, so I had to run this first -> `brew install dbus`.

**Comment by tkluck** [comment]
Thanks for reporting! That needs a platform exclusion like https://github.com/tkluck/pac4cli/pull/25/files because we don't use dbus on mac. Pull request welcome (or I'll get to it later today).

**Comment by gil** [comment]
Thanks, just send the PR!
