### ISSUE TITLE
support installation in /usr, depend on system packages

### ISSUE THREAD

**Issue by tkluck** [tkluck/pac4cli#4]
This requires at least the following:
 - rename `main.py` to just `pac4cli`; put it in `$PREFIX/bin`
 - put `proxy.py` in `$PREFIX/lib/python3/site-packages/pac4cli`
 - (for debian) package txdbus and the new version of python3-systemd

It probably means we want `make install` to work with system packages and install in `/usr/local`, and make the virtualenv `/opt` installation a supported but non-default option. `make opt-install` or something.

Helpful:
 - make pacparser installable through pip and remove it as a git-submodule.
 - other?

**Comment by kdehairy** [comment]
I totally agree. I was just going to ask you why do we have pacparser as a submodule. This prevented me from adding the package as a dependency as usual. I thought you rely on a specific version of pacparser.

**Comment by kdehairy** [comment]
Thanks to @tkluck
