### ISSUE TITLE
Explicitly specify IPv6 preference in CLI

### ISSUE THREAD

**Issue by kdehairy** [tkluck/pac4cli#51]
#### `pac4cli --bind localhost --ipv6`
This will have the effect of preferring IPv6 interface over IPv4 interface if both are present.

#### `pac4cli --bind 127.0.0.0 --ipv6`
Has no effect

**Comment by tkluck** [comment]
It's also an option not to do any name resolution, and just do `--bind 127.0.0.1` or `--bind [::1]`. We'd allow passing `--bind` several times to listen on several interfaces.

Meanwhile, the user (or the package maintainer, i.e. our archlinux/debian configuration) is responsible for making sure that we bind to the same things as what we put in `http_proxy=`.

That feels like the cleaner option to me; what do you think?

**Comment by kdehairy** [comment]
Agree. I have to say I was per-maturely enthusiastic about this feature :)

**Comment by kdehairy** [comment]
Not beneficial as agreed
