### ISSUE TITLE
How can I get this to run in Debian 9

### ISSUE THREAD

**Issue by erenoglu** [tkluck/pac4cli#70]
I tried to build it in Debian 9 but faced too many issues. 
Is there any way or guide on how to do it? Or is it impossible due to dependencies?

**Comment by kdehairy** [comment]
Can you please provide more details?

**Comment by erenoglu** [comment]
We can close this, I had to install various dependencies and development packages, once done, I was able to run the requirements.txt and then make install.

I also had to change the service file a bit to remove dynamic user and assign it to my own user to make it start with systemd, else it was giving some error that the user had no rights to access some files.

**Comment by kdehairy** [comment]
Thnx @erenoglu. It would be great if you opened another ticket regarding the access rights issue you faced.
