### ISSUE TITLE
PPA for focal (20.04)

### ISSUE THREAD

**Issue by johnsonb88** [tkluck/pac4cli#75]
I don't see packages for Ubuntu 20.04 ("focal") in the tkluck/pac4cli PPA.  It only seems to have packages up through 19.04 ("disco").  Would you consider adding a build for 20.04, since it's a new long-term support (LTS) release?

Pac4cli is an awesomely useful package!  I don't actually use it much for CLI apps, but I use it as a systemwide proxy for browsers, VMs, and everything else I use.  It makes it absolutely seamless to move between my corporate network and unproxied networks outside the office.  Great job!

Thanks,
Brian

**Comment by tkluck** [comment]
Apologies for the oversight! Done.

**Comment by johnsonb88** [comment]
Thanks!  Looks like it needs txdbus as well...
