### ISSUE TITLE
txdbus in PPA for focal

### ISSUE THREAD

**Issue by johnsonb88** [tkluck/pac4cli#76]
Thanks for building the PPA for Ubuntu 20.04 (focal fossa) under issue #75.  The pac4cli package is available for download.  However, launchpad only shows txdbus packages up through 19.04.  The missing package is causing an unmet dependency:
```
$ sudo apt install pac4cli
   ...
The following packages have unmet dependencies:
 pac4cli : Depends: python3-txdbus but it is not installable
```
Could you enable txdbus in the PPA as well?  Or is there somewhere else I should be installing python3-txdbus from?

Thanks!
Brian

**Comment by tkluck** [comment]
Oops, sorry for skipping that one. (I wish launchpad would automate this for me whenever there's a new distribution series.) I requested the builds now!
