### ISSUE TITLE
txdbus in PPA for focal - again

### ISSUE THREAD

**Issue by johnsonb88** [tkluck/pac4cli#77]
Thanks for working on txdbus in #76!  However, it looks like it only got enabled for 19.10.  It's still not there for 20.04 (focal)...

Thanks,
Brian

**Comment by tkluck** [comment]
Thanks for noticing. This looks like an issue related to the python3 migration: https://code.launchpad.net/~tkluck/+recipe/txdbus shows issues with missing `python-*` dependencies. Let me see what I can do.

**Comment by tkluck** [comment]
Okay I think this one fixed it now: https://git.launchpad.net/~tkluck/txdbus/commit/?id=f6f8c299d2def321cbf74c0db9c0fbba5dfeca58 Could you verify that it did and then close this issue?

**Comment by johnsonb88** [comment]
I'm using xubuntu 20.04.  The installation pulled in quite a bit of python:

bash> sudo apt install pac4cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libllvm9
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  python3-attr python3-automat python3-click python3-colorama
  python3-constantly python3-hamcrest python3-hyperlink python3-incremental
  python3-openssl python3-pacparser python3-pyasn1 python3-pyasn1-modules
  python3-service-identity python3-twisted python3-twisted-bin python3-txdbus
  python3-zope.interface
Suggested packages:
  python-attr-doc python-openssl-doc python3-openssl-dbg python3-tk
  python3-pampy python3-qt4 python3-serial python3-wxgtk2.8
  python3-twisted-bin-dbg python-txdbus-doc
The following NEW packages will be installed:
  pac4cli python3-attr python3-automat python3-click python3-colorama
  python3-constantly python3-hamcrest python3-hyperlink python3-incremental
  python3-openssl python3-pacparser python3-pyasn1 python3-pyasn1-modules
  python3-service-identity python3-twisted python3-twisted-bin python3-txdbus
  python3-zope.interface
0 upgraded, 18 newly installed, 0 to remove and 40 not upgraded.
Need to get 2,771 kB of archives.
After this operation, 17.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 

But everything seemed to install correctly, and pac4cli is successfully delivering web pages.  So it seems to work.  Thanks!

Brian
